#!/bin/sh
# eclean.sh: this utility can be used to clean up tag files generated by Cscope, 
# Global and Ctags, or svn files.

#set -x

DEF_OPTION="t"
DEF_DEST="$PWD"
VIM_BACKUP="*~"
SVN_INFO=".svn"
GIT_INFO=".git"
CSCOPE_FILES="cscope.files cscope.in.out cscope.out cscope.po.out"
GLOBAL_FILES="gtags.files GTAGS GPATH GRTAGS"
CTAGS_FILES="tags"

usage()
{
    echo ""
    echo "Usage: $0 [OPTION] [DEST]"
    echo "OPTION: -t, clean up tag files(default option);"
    echo "        -s, clean up svn info."
    echo "        -g, clean up git info."
    echo "DEST: current directory if not set"
}

while getopts "stg" option
do
    case $option in
        s)  if [ "$ECLEAN_MODE" = "t" ]; then
            ECLEAN_MODE="st"
            elif [ "$ECLEAN_MODE" = "g" ]; then
            ECLEAN_MODE="sg"
            elif [ "$ECLEAN_MODE" = "tg" ]; then
            ECLEAN_MODE="stg"
            else 
            ECLEAN_MODE="s"
            fi
        ;;
        t)  if [ "$ECLEAN_MODE" = "s" ]; then
            ECLEAN_MODE="st"
            elif [ "$ECLEAN_MODE" = "g" ]; then
            ECLEAN_MODE="tg"
            elif [ "$ECLEAN_MODE" = "sg" ]; then
            ECLEAN_MODE="stg"
            else 
            ECLEAN_MODE="t"
            fi
        ;;
        g)  if [ "$ECLEAN_MODE" = "s" ]; then
            ECLEAN_MODE="sg"
            elif [ "$ECLEAN_MODE" = "t" ]; then
            ECLEAN_MODE="tg"
            elif [ "$ECLEAN_MODE" = "st" ]; then
            ECLEAN_MODE="stg"
            else 
            ECLEAN_MODE="g"
            fi
        ;;
        ?)  usage
            exit 1
        ;;
    esac
done

shift $(($OPTIND-1))
dst_dir=$1
# no DEST argument.
if [ -z "$dst_dir" ]; then
    dst_dir=$DEF_DEST
fi
# no options
if [ -z "$ECLEAN_MODE" ]; then
    ECLEAN_MODE=$DEF_OPTION
fi

if [ -d "$dst_dir" ]; then
    case $ECLEAN_MODE in
        s)  find $dst_dir -type d -name "$SVN_INFO" | xargs rm -rf #better choice! 
            echo "Cleaning up .svn for $dst_dir..."
            ;;
        g)  find $dst_dir -type d -name "$GIT_INFO" | xargs rm -rf #better choice! 
            echo "Cleaning up .git for $dst_dir..."
            ;;
        t)  #find $dst_dir -type f -name "$VIM_BACKUP" -exec rm -f {} \;
            rm -f $CSCOPE_FILES $GLOBAL_FILES $CTAGS_FILES
            echo "Cleaning up vim backup files and tags files for $dst_dir..."
            ;;
        st) find $dst_dir -type d -name "$SVN_INFO" | xargs rm -rf
            echo "Cleaning up .svn..."
            find $dst_dir -type f -name "$VIM_BACKUP" -exec rm -f {} \;
            rm -f $CSCOPE_FILES $GLOBAL_FILES $CTAGS_FILES
            echo "Cleaning up vim backup files and tags files for $dst_dir..."
            ;;
        # TODO
    esac
else
    echo "$dst_dir NOT exist!"
    usage
fi


